app:
  name: "Mi App"
api:
  url: "https://example.com"
  timeout-ms: 2000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    es.fplumara.dam2.springdemo.services: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    